name: tic_tac_bet
description: "Tic Tac Toe with betting mechanics â€” Betclic tech test"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Immutable entities
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Local persistence
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.1.0

  # Navigation
  go_router: ^14.8.1

  # Animations
  flutter_animate: ^4.5.2

  # Typography
  google_fonts: ^6.2.1

  # Backend
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.14
  freezed: ^3.0.0
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  hive_ce_generator: ^1.8.0

  # Testing
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
